module RBS
  class Parser
    def self.parse_method_type: (Buffer, ?line: Integer, ?column: Integer, ?variables: Array[Symbol]) -> MethodType

    def self.parse_type: (Buffer, ?line: Integer, ?column: Integer, ?variables: Array[Symbol]) -> Types::t

    def self.parse_signature: (Buffer, ?line: Integer, ?column: Integer) -> Array[AST::Declarations::t]

    private

    %a{no-defn}
    def self._parse_type: (Buffer, Integer line, Integer column, Array[Symbol] variables) -> Types::t

    %a{no-defn}
    def self._parse_method_type: (Buffer, Integer line, Integer column, Array[Symbol] variables) -> MethodType

    %a{no-defn}
    def self._parse_signature: (Buffer, Integer line, Integer column) -> Array[AST::Declarations::t]
  end
end
